import { ROUTES } from "@/config/routes";

export const indexableRoutes: ReadonlyArray<string> = [
  ROUTES.home,
  ROUTES.platform,
  ROUTES.contextGraph,
  ROUTES.engineeringIntelligence,
  ROUTES.projectHealth,
  ROUTES.evidenceFirstAi,
  ROUTES.mcp,
  ROUTES.useCases,
  ROUTES.solutions,
  ROUTES.integrations,
  ROUTES.integrationsGithub,
  ROUTES.integrationsJira,
  ROUTES.learn,
  ROUTES.learnContextDiagnosis,
  ROUTES.research,
  ROUTES.blog,
  ROUTES.trust,
  ROUTES.trustSecurity,
  ROUTES.trustPrivacy,
  ROUTES.trustData,
  ROUTES.trustNoSurveillance,
  ROUTES.contact,
  ROUTES.compare,
  ROUTES.engineeringIntelligenceSeo,
  ROUTES.engineeringContext,
  ROUTES.engineeringKnowledgeGraph,
  ROUTES.engineeringOrganizationalMemory,
  ROUTES.aiCodingAgentContext,
  ROUTES.engineeringOnboarding,
  ROUTES.architectureKnowledge,
  ROUTES.engineeringInvestigation,
];
