/** Single source of truth for internal links, sitemap, metadata paths, and nav hrefs. */
export const ROUTES = {
  home: "/",
  platform: "/platform",
  contextGraph: "/platform/context-graph",
  engineeringIntelligence: "/platform/engineering-intelligence",
  projectHealth: "/platform/project-health",
  evidenceFirstAi: "/platform/evidence-first-ai",
  mcp: "/platform/mcp",
  useCases: "/use-cases",
  solutions: "/solutions",
  integrations: "/integrations",
  integrationsGithub: "/integrations/github",
  integrationsJira: "/integrations/jira",
  compare: "/compare",
  learn: "/learn",
  learnContextDiagnosis: "/learn/engineering-context-and-diagnosis",
  research: "/research",
  blog: "/blog",
  trust: "/trust",
  trustSecurity: "/trust/security",
  trustPrivacy: "/trust/privacy",
  trustData: "/trust/data",
  trustNoSurveillance: "/trust/no-surveillance",
  contact: "/contact",
  engineeringIntelligenceSeo: "/engineering-intelligence",
  engineeringContext: "/engineering-context",
  engineeringKnowledgeGraph: "/engineering-knowledge-graph",
  engineeringOrganizationalMemory: "/engineering-organizational-memory",
  aiCodingAgentContext: "/ai-coding-agent-context",
  engineeringOnboarding: "/engineering-onboarding",
  architectureKnowledge: "/architecture-knowledge",
  engineeringInvestigation: "/engineering-investigation",
  compareHatica: "/compare/nudgeio-vs-hatica",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
